#!/bin/bash

# parse arguments
declare -a BM
BM=()
PROP_FILE=""
WITNESS_FILE=""

TOOL_BINARY=jpf-core/bin/jpf
FIND_OPTIONS="-name '*.java'"

while [ -n "$1" ] ; do
  case "$1" in
    --32|--64) BIT_WIDTH="${1##--}" ; shift 1 ;;
    --propertyfile) PROP_FILE="$2" ; shift 2 ;;
    --graphml-witness) WITNESS_FILE="$2" ; shift 2 ;;
    --version) date -r jpf-symbc/build/jpf-symbc.jar ; exit 0 ;;
    *) SRC=(`eval "find $1 $FIND_OPTIONS"`) ; BM=("${BM[@]}" "${SRC[@]}") ; shift 1 ;;
  esac
done

if [ -z "${BM[0]}" ] || [ -z "$PROP_FILE" ] ; then
  echo "Missing benchmark or property file"
  exit 1
fi

if [ ! -s "${BM[0]}" ] || [ ! -s "$PROP_FILE" ] ; then
  echo "Empty benchmark or property file"
  exit 1
fi

echo "PROP_FILE=$PROP_FILE"
  ASSERTION_MODE="FALSE"
  RUNTIME_EXCEPTION_MODE="FALSE"
  grep "assert" $PROP_FILE
  if [ $? -eq 0 ]; then
    ASSERTION_MODE="TRUE"
  fi

  grep "Exception" $PROP_FILE
  if [ $? -eq 0 ]; then
    RUNTIME_EXCEPTION_MODE="TRUE"
  fi

echo "ASSERTION_MODE=$ASSERTION_MODE"
echo "RUNTIME_EXCEPTION_MODE=$RUNTIME_EXCEPTION_MODE"

LOG=`mktemp -t jpf-log.XXXXXX`
DIR=`mktemp -d -t jpf-benchmark.XXXXXX`

trap "rm -rf $DIR" EXIT

mkdir -p $DIR/target/classes

/usr/lib/jvm/java-8-openjdk-amd64/bin/javac -g -cp $CLASSPATH_ADDED:$DIR/target/classes -d $DIR/target/classes "${BM[@]}"

# create configuration file
echo "target=Main" > $DIR/config.jpf
echo "classpath=`pwd`/jpf-symbc/build/classes:$DIR/target/classes:$CLASSPATH_ADDED" >> $DIR/config.jpf
echo "symbolic.dp=z3bitvector" >> $DIR/config.jpf
echo "symbolic.bvlength=64" >> $DIR/config.jpf
echo "search.depth_limit=13" >> $DIR/config.jpf
echo "symbolic.strings=true" >> $DIR/config.jpf
echo "symbolic.string_dp=z3str3" >> $DIR/config.jpf
echo "nullPointer.exception=false" >> $DIR/config.jpf
echo "symbolic.string_dp_timeout_ms=3000" >> $DIR/config.jpf
echo "symbolic.lazy=on" >> $DIR/config.jpf
echo "symbolic.arrays=true" >> $DIR/config.jpf
echo "listener = .symbc.SymbolicListener" >> $DIR/config.jpf
if [ $RUNTIME_EXCEPTION_MODE = "TRUE" ] ; then
  echo "runtime.exception=true" >> $DIR/config.jpf
  #echo "search.multiple_errors = true" >> $DIR/config.jpf
fi
echo $DIR/config.jpf

# run SPF
export LD_LIBRARY_PATH=`pwd`/jpf-symbc/lib:$LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
if test -z "$JVM_FLAGS"; then
  JVM_FLAGS="-Xmx1024m -ea"
fi
/usr/lib/jvm/java-8-openjdk-amd64/bin/java $JVM_FLAGS -jar $(pwd)/jpf-core/build/RunJPF.jar $DIR/config.jpf | tee $LOG

# check the result
if [ $ASSERTION_MODE = "TRUE" ]; then
  echo "inside assertion_mode=true"

  grep "no errors detected" $LOG > /dev/null
  NO_ERRORS=$?

  grep "java.lang.*Exception" $LOG > /dev/null
  JAVA_EXCEPTION=$?

  grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
  ASSERTION_ERROR=$?

  if [ $NO_ERRORS -eq 0 ] || ([ $JAVA_EXCEPTION -eq 0 ] && [ $ASSERTION_ERROR -ne 0 ]); then
    echo "SAFE"
  elif [ $ASSERTION_ERROR -eq 0 ]; then
    echo "UNSAFE"
  else
    echo "UNKNOWN"
  fi

elif [ $RUNTIME_EXCEPTION_MODE = "TRUE" ]; then
  echo "inside runtime_exception_mode=true"

  # Check for assertion errors AND no java exceptions OR no errors detected
  grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
  ASSERTION_ERROR=$?

  grep "java.lang.*Exception" $LOG > /dev/null
  JAVA_EXCEPTION=$?

  grep "no errors detected" $LOG > /dev/null
  NO_ERRORS=$?

  if ([ $ASSERTION_ERROR -eq 0 ] && [ $JAVA_EXCEPTION -ne 0 ]) || [ $NO_ERRORS -eq 0 ]; then
    echo "SAFE"
  elif [ $JAVA_EXCEPTION -eq 0 ]; then
    echo "UNSAFE"
  else
    echo "UNKNOWN"
  fi

else
  echo "unsupported case. Failing"
  exit 1
fi
