/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class concolic_Bessel */

#ifndef _Included_concolic_Bessel
#define _Included_concolic_Bessel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     concolic_Bessel
 * Method:    bessely0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_concolic_Bessel_bessely0
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
