name: Gradle Package

on:
  push:
    branches: [ main-gk ]
  pull_request:
    branches: [ main-gk ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Build jpf-core jars with Gradle
      run: ./gradlew :jpf-core:build
    - name: Build jpf-symbc with Gradle
      run: ./gradlew :jpf-symbc:check
