name: Gradle Package

on:
  push:
    branches: [ main-gk ]
  pull_request:
    branches: [ main-gk ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
      
    - name: Run multi-line Script
        
        
    - name: Build jpf-core and jpf-symbc with Gradle
    - run: |
        echo what is in this directory?
        ls -a
        echo Is java installed?
        java -version
